version: '3.8'
# definir container
services:

  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    volumes:
      - db_data:/var/lib/mysql
  # spring app
  backend:
    image: amalennj/achat:1-1
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  Frontend:
    image: amalennj/achatfront
    restart: unless-stopped
    ports:
      - "4200:4200"

volumes:
  db_data: